version: '3'

networks:
  camunda-vs-zeebe:

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - camunda-vs-zeebe

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9093:9093"
    networks:
      - camunda-vs-zeebe
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: >
        company-scoring-response:1:1,
        scoring-response:1:1

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    #    image: elasticsearch:8.1.2   ! not working with this version
    ports:
      - "9200:9200"
    networks:
      - camunda-vs-zeebe
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  #    volumes:
  #      - elasticsearch_data:/usr/share/elasticsearch/data

  zeebe:
    container_name: zeebe
    image: camunda/zeebe:8.0.0
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    networks:
      - camunda-vs-zeebe
    volumes:
      - ./zeebe/zeebe-hazelcast-exporter-1.0.1-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./zeebe/application.yaml:/usr/local/zeebe/config/application.yaml
    depends_on:
      - elasticsearch

  operate:
    container_name: operate
    image: camunda/operate:8.0.0
    ports:
      - "8083:8080"
    networks:
      - camunda-vs-zeebe
    volumes:
      - ./operate/application.yml:/usr/local/operate/config/application.yml
    depends_on:
      - zeebe
      - elasticsearch

  monitor:
    container_name: monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    ports:
      - "8082:8082"
    networks:
      - camunda-vs-zeebe
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./monitor/application.yaml:/application.yaml
    depends_on:
      - zeebe

#  tasklist:
#    container_name: tasklist
#    image: camunda/tasklist:8.0.0
#    ports:
#      - "8084:8080"
#    networks:
#      - camunda-vs-zeebe
#    environment:
#      - GRAPHQL_PLAYGROUND_ENABLED=true
#      - GRAPHQL_PLAYGROUND_SETTINGS_REQUEST_CREDENTIALS=include
#    volumes:
#      - ./tasklist/application.yml:/app/resources/application.yml
#    depends_on:
#      - zeebe
#      - elasticsearch

  storage:
    container_name: storage
    build:
      context: ./../storage
    image: storage:latest
    ports:
      - "8091:8080"
    networks:
      - camunda-vs-zeebe

  scoring:
    container_name: scoring
    build:
      context: ./../scoring
    image: scoring:latest
    ports:
      - "8092:8080"
    networks:
      - camunda-vs-zeebe
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092

#  zeebe-app:
#    container_name: zeebe-app
#    build:
#      context: ./../zeebe-app
#    image: zeebe-app:latest
#    ports:
#      - "8080:8080"
#    networks:
#      - camunda-vs-zeebe
#    depends_on:
#      - storage
#      - scoring
#      - kafka
#    environment:
#      - services.storage=http://storage:8080/
#      - services.scoring=http://scoring:8080/
#      - spring.kafka.bootstrapservers=kafka:9092
#      - zeebe.client.broker.gateway-address=zeebe:26500
