spring:
  kafka:
    username: camunda-app
    bootstrap-servers: localhost:9093
    consumer:
      group-id: ${spring.kafka.username}.group
      client-id: ${spring.kafka.username}.client
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        allow.auto.create.topics: false
    properties:
      security.protocol: PLAINTEXT

springdoc:
  packagesToScan: ru.akonyaev.zeebe.controller
  pathsToMatch: /process/**

services:
  storage: http://localhost:8091/
  scoring: http://localhost:8092/

zeebe:
  client:
    # local zeebe ---------------------------------
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    # zeebe in cloud ------------------------------:
#    cloud:
#      auth-url: 'https://login.cloud.camunda.io/oauth/token'
#      base-url: 'zeebe.camunda.io'
#      region: 'bru-2'
#      cluster-id: '***'
#      client-id: '***'
#      client-secret: '***'
    worker:
      max-jobs-active: 256  # 32 by default
      threads: 16 # 1 by default
    job:
      poll-interval: 100 # 100 msec by default

